apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
  namespace: argo-workflows
spec:
  entrypoint: print-message     # Fields other than "arguments" and "templates" not supported in v2.4 - v2.6
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: entrypoint 
      steps:
      - name: print-message
        template: print-message
      - name: git-clone
        template: git-clone
    - name: print-message
      inputs:
        parameters:
          - name: message
      container:
        image: busybox
        command: [echo]
        args: ["{{inputs.parameters.message}}"]
    - name: git-clone
      inputs:
        artifacts:
        - name: argo-source
          path: /src
          git:
            repo: https://github.com/ricardofukuda-org/argo-workflows-test.git
            revision: "master"
            usernameSecret:
              name: argo-workflows-github-creds
              key: username
            passwordSecret:
              name: argo-workflows-github-creds
              key: password
      container:
        image: golang:1.10
        command: [sh, -c]
        args: ["git status && ls && cat VERSION"]
        workingDir: /src